name: testing1628

on:
  workflow_dispatch:

jobs:
  reproduce:
    runs-on: ubuntu-latest
    steps:
      - name: Create a symlinked cycle
        run: |
          mkdir -p /tmp/real
          echo '{"volta": {"extends": "./loop/pkg.json"}}' > /tmp/real/pkg.json
          ln -s /tmp/real /tmp/real/loop
      - id: setup
        continue-on-error: true
        uses: v-gowridurgad/setup-node@fix-1628
        with:
          node-version-file: /tmp/real/pkg.json
     
