name: testing1628

on:
  workflow_dispatch:

jobs:
  reproduce:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

     

      - name: Run setup-node against cyclic manifest
        uses: v-gowridurgad/setup-node@fix-1628
        with:
          node-version-file: mixed.json
